version: "3"

services:
  gext-server:
    build: ./
    environment:
      GEXT_ADDRESS: "0.0.0.0"
      GEXT_DATASTORE_MYSQL_DSN: "root:password1@tcp(db:3306)/gext"
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "80:8080"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: gext
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - backend
    expose:
      - "3306"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

volumes:
  db-data:

networks:
  backend:
